config/routes.rb
Rails.application.routes.draw do
  resources :posts do
  	#post 'comments', to: 'comments#create'
    resources :comments, only: [:create, :destroy]
  end
  root to: 'posts#index'
  get 'pages/personal', to: "pages#personal"
  get 'pages/tabl'
  get 'pages/custumizer'
  resources :pages do
    collection do
      get :searcher
    end
   end
  get 'posts/tagged', to: "posts#tagged", as: :tagged
  devise_for :users
  resources :users do
    resources :posts
  end
  
  resources :posts do 
    member do
      put "like", to: "posts#vote"
    end
  end
  resources :users do
    collection do
      post :edit_multiple
    end
   end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
  validates :body , presence: true , allow_blank: false
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_post
  before_action :authenticate_user!
	def create

    @comment = @post.comments.new(comment_params)
    @comment.user = current_user
    @comment.save
    #redirect_back(fallback_location: root_path)
    #redirect_to post_path(@post)

  end
  def destroy

    @comment = @post.comments.find(params[:id])
    @comment_id = @comment.id
    @comment.destroy
    #redirect_to post_path(@post)
  end

  private

    def set_post
      @post = Post.find(params[:post_id])
    end

    def comment_params
      params.require(:comment).permit(:body, :post_id)
    end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div id="comment-<%= comment.id %>">
	<section class="comment-list">
	<!-- First Comment -->
	<header class="text-left" style="font-size: 15px;">
	  <div class="comment-user"><i class="fa fa-user"></i> <%= comment.user.username %>
	</div>
	  <time class="comment-date" ><i class="fa fa-clock-o"></i> <%= comment.created_at.strftime("%e %B %y %H : %M") %></time>
	</header>
	<div class="comment-post">
	  <p style="font-size: 20px;"> <%= comment.body %></p>
	  <% if current_user %>
	  <li><% if current_user == comment.user || current_user.admin %>
		<%= link_to "Delete", post_comment_path(@post, comment), class:"btn btn-secondary btn-sm",method: :delete, remote: true, style:'float: right' %></li>
		<%end%>
		<%end%>
	</div>
	</section>
	<hr/>
	<br/>
</div>

app/views/comments/create.js.erb
$('#comment_pane').prepend("<%= j render @comment  %>");
$('#comment_body').val('');

app/views/comments/destroy.js.erb
$('#comment-<%= @comment_id %>').html('');