config/routes.rb
Rails.application.routes.draw do
  resources :posts do
  	#post 'comments', to: 'comments#create'
    resources :comments, only: [:create, :destroy]
  end
  root to: 'posts#index'
  get 'pages/personal', to: "pages#personal"
  get 'pages/tabl'
  get 'pages/custumizer'
  resources :pages do
    collection do
      get :searcher
    end
   end
  get 'posts/tagged', to: "posts#tagged", as: :tagged
  devise_for :users
  resources :users do
    resources :posts
  end
  
  resources :posts do 
    member do
      put "like", to: "posts#vote"
    end
  end
  resources :users do
    collection do
      post :edit_multiple
    end
   end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/pages/custumizer.html.erb
<head><link href="//netdna.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script></head>
<link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.1.0/css/font-awesome.min.css"/>
 <%= render 'posts/navsing' %>
<div id="canvas-wrapper" class="editor-area">
  <div class="canvas-bg-wrapper"> 
      <canvas width="580" height="580" id="c"></canvas>
  </div>
</div>
<div class="controls">
<input type="file" id="imgLoader"><br>
  <%= submit_tag 'Insert Text', :onClick => "insertText();", :class => 'btn btn-secondary'%><br><br>
  <%= submit_tag 'Male model', :onClick => "insertMale();", :class => 'btn btn-secondary'%><br><br>
  <%= submit_tag 'Female model', :onClick => "insertFemale();", :class => 'btn btn-secondary'%><br><br>
  <%= submit_tag 'Save statement', :onClick => "toJSON();", :class => 'btn btn-secondary'%><br><br>
  <%= submit_tag 'Upload last statment', :onClick => "fromJSON();", :class => 'btn btn-secondary'%><br><br>
  <%= submit_tag 'Delete Object', :onClick => "deleteObjects();", :class => 'btn btn-secondary'%><br><br>
  <div id="textMenu" class="hideOperations">
      <button class="btn btn-secondary" id="underline">UnderLine</button><br><br>
  <input type="range" min="5" max="150" value="40" id="size"><br>
    <input type="range" min="0.1" max="5" value="0.1" id="height"><br>
  <input class="btn btn-secondary" type="color" id="color">
  <input class="btn btn-secondary" type="color" id="bg-color"><br><br>
  <button class="btn btn-secondary" id="italic">Style</button>
  <button class="btn btn-secondary" id="centered">Centre</button><br><br>
  <button class="btn btn-secondary" id="left">Left</button>
  <button class="btn btn-secondary" id="right">Right</button>
  </div>
  
</div>
<%= javascript_include_tag 'design.js' %>

app/views/pages/personal.html.erb
<head><link href="//netdna.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script></head>
<link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.1.0/css/font-awesome.min.css"/>
<%= render 'posts/navsing' %>
<h2> Welcome <%= current_user.username %></h2>
    
    <% @posts.each do |post| %>
      <div class="container">
          <div class="well">
              <div class="media">
                <a class="pull-left" href="#">
                <%- if post.image.attached? %>
                <div style="width:300px; height: auto">
                <%=image_tag(post.image, style: 'width:100%') %>
                </div>
                <%-end%>
              </a>
              <div class="media-body">
                <h4 class="media-heading"><%= post.title %></h4>
                  <p class="text-right"><%= post.user.username %></p>
                  <p><%= post.description %></p>
                  <ul class="list-inline list-unstyled">
  <li><span><p><i class="fa fa-thumbs-up fa-1x"> <%= post.get_upvotes.size %> likes</i></p></span></li>
                    <li>|</li>
                    <span><i class="glyphicon glyphicon-comment"></i> <%= pluralize(post.comments.count, "comment") %></span>
                    <li>|</li>
                    <li><span><p></p><%= link_to 'Show', post, class:"btn btn-secondary" %></span></li>
                    <li>|</li>
                    <li><span><p></p><%= link_to 'Edit', edit_post_path(post), class:"btn btn-secondary" %></span></li>
                    <li>|</li>
                    <li><span><p></p><%= link_to 'Destroy', post, class:"btn btn-secondary", method: :delete, data: { confirm: 'Are you sure?' } %></span></li>
                    <li>|</li>
              </ul>
                 <p style="font-size: 25px;"> Price: <%= post.price %></p>
               </div>
            </div>
          </div>
        </div>
    <% end %> 
  

    
    

app/views/pages/searcher.html.erb
<head><link href="//netdna.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script></head>
<link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.1.0/css/font-awesome.min.css"/>

<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">
<% if current_user %>
 <%= render 'posts/navsing' %>
<% else %>
  <%=render 'posts/nav' %>
<% end %>
<%= form_for posts_path, :method => 'get' do %> 
  <div class="container">
    <br/>
  <div class="row justify-content-center">
                        <div class="col-12 col-md-10 col-lg-8">
                            <form class="card card-sm">
                                <div class="card-body row no-gutters align-items-center">
                                    <div class="col-auto">
                                        <i class="fas fa-search h4 text-body"></i>
                                    </div>
                                    <!--end of col-->
                                    <div class="col">
                                       <%= text_field_tag :search, params[:search], class:"form-control form-control-lg form-control-borderless", placeholder:"Search topics or keywords"%>
                                    </div>
                                    <!--end of col-->
                                    <div class="col-auto">
                                       <%= submit_tag "Search", :name => nil,class:"btn btn-lg btn-success" %>
                                    </div>
                                    <!--end of col-->
                                </div>
                            </form>
                        </div>
                        <!--end of col-->
                    </div>
</div>
  
<% end %>

  
  <% @results.each do |result| %>
   <div class="container">
          <div class="well">
              <div class="media">
                <a class="pull-left" href="#">
                <%- if result.image.attached? %>
                <div style="width:300px; height: auto">
                <%=image_tag(result.image, style: 'width:100%') %>
                </div>
                <%-end%>
              </a>
              <div class="media-body">
                <h4 class="media-heading"><%= result.title %></h4>
                  <p class="text-right"><%= result.user.username %></p>
                  <p><%= result.description %></p>
                  <ul class="list-inline list-unstyled">
  <li><span><p><i class="fa fa-thumbs-up fa-1x"> <%= result.get_upvotes.size %> likes</i></p></span></li>
                    <li>|</li>
                    <span><i class="glyphicon glyphicon-comment"></i> <%= pluralize(result.comments.count, "comment") %></span>
                    <li>|</li>
                    <li><span><p></p><%= link_to 'Show', result, class:"btn btn-secondary" %></span></li>
                    <li>|</li>
              </ul>
              <p style="font-size: 25px;"> Price: <%= result.price %></p>
               </div>
            </div>
          </div>
        </div>
    <% end %> 

app/views/pages/tabl.html.erb
<head><link href="//netdna.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script></head>
<link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.1.0/css/font-awesome.min.css"/>
<%= render 'posts/navsing' %>
<%= form_tag edit_multiple_users_path, method: :post do %> 
    <div class="btn-group" role="group" aria-label="Basic example">
     <%= submit_tag 'Delete', :class => 'btn btn-secondary'%>
     <%= submit_tag 'Lock', :class => 'btn btn-secondary'%>
     <%= submit_tag 'Unlock', :class => 'btn btn-secondary'%>
     <%= submit_tag 'Admin', :class => 'btn btn-secondary'%>
    </div>
    <br>
    <table class="table">
      <thead class="thead-dark">
        <tr>
          <th><%= check_box_tag('check_all', 'check_all', false, :onClick => "checkAll(this);") %></th>
          <th scope="col">Email</th>
          <th scope="col">CreatedAt</th>
          <th scope="col">Lock State</th>
          <th scope="col">Status</th>
        </tr>
      </thead>
      <tbody>
        <% @users.each do |user| %>
      <tr>
          <th scope="row"><%= check_box_tag('users_id[]', user.id)%></th>
          <td><%= user.email %></td>
          <td><%= user.created_at %></td>
          <td><%= user.access_locked? ? "Locked" : "Unlocked" %></td>
          <td><%= user.admin ? "Admin" : "User" %></td>
      </tr>
        <%end%>
      </tbody>
    </table>
 <%end%>