config/routes.rb
Rails.application.routes.draw do
  resources :posts do
  	#post 'comments', to: 'comments#create'
    resources :comments, only: [:create, :destroy]
  end
  root to: 'posts#index'
  get 'pages/personal', to: "pages#personal"
  get 'pages/tabl'
  get 'pages/custumizer'
  resources :pages do
    collection do
      get :searcher
    end
   end
  get 'posts/tagged', to: "posts#tagged", as: :tagged
  devise_for :users
  resources :users do
    resources :posts
  end
  
  resources :posts do 
    member do
      put "like", to: "posts#vote"
    end
  end
  resources :users do
    collection do
      post :edit_multiple
    end
   end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments, dependent: :destroy
  has_one_attached :image
  belongs_to :user
  acts_as_votable
  acts_as_taggable_on :tags
 
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy, :searcher, :vote, :tagged]
  before_action :authenticate_user!, except: [:show, :index]
  respond_to :js, :html, :json
  
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
    @results = Post.search(params[:search], :order => 'created_at DESC')
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @comment = Comment.new
    @comments = @post.comments.order("created_at DESC")
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit 

  end
  def vote
    if !current_user.liked? @post
      @post.liked_by current_user
    elsif current_user.liked? @post
      @post.unliked_by current_user
    end
  end
  def tagged
    if params[:tag].present?
      @posts = Post.tagged_with(params[:tag])
    else
      @posts = Post.all
    end
  end
  

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user=current_user
    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :description, :image, :user_id, :tag_list, :price)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<head><link href="//netdna.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script></head>
<link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.1.0/css/font-awesome.min.css"/>
<%= render 'posts/navsing' %>
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="main-divv">
  <div class="form-group row">
    <%= form.label :Theme, class:"col-4 col-form-label"%>
    <div class="col-8">
      <%= form.text_field :title , class:"form-control"%>
    </div>
  </div>

  <div class="form-group row">
      <%= form.label :image,class:"col-4 col-form-label" %>
    <div class="col-8 ui-widget">
      <%= form.file_field :image , class:"btn btn-secondary" %>
    </div>
  </div>


  <div class="form-group row">
      <%= form.label :Description ,class:"col-4 col-form-label"%>
    <div class="col-8">
      <%= form.text_area :description, class:"form-control" %>
    </div>
  </div> 

  
  <div class="form-group row">
     <%= form.label :Price, class:"col-4 col-form-label"%>
    <div class="col-8">
      <%= form.text_field :price , class:"form-control"%>
    </div>
  </div>

  <div class="actions">
    <div class="sumbit-control">
      <%= form.submit :class => "btn btn-primary btn-lg btn-block" %>
    </div>
  </div>
</div>
<% end %>

app/views/posts/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to "Sign In", new_user_session_path, class:"nav-link" %>
      </li>
      <li class="nav-item">
         <%= link_to "Sign Up", new_user_registration_path, class:"nav-link" %>
      </li>
      <li class="nav-item">
         <%= link_to "Searcher", searcher_pages_path, class:"nav-link" %>
      </li>
    </ul>
  </div>
</nav>

app/views/posts/_navsing.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to "Sign Out", destroy_user_session_path, class:"nav-link", :method => :delete %>
      </li>
      <li class="nav-item">
         <%= link_to "Personal Cabinet", pages_personal_path, class:"nav-link" %>
      </li>
      <li class="nav-item">
         <%= link_to "Custumizer", pages_custumizer_path, class:"nav-link" %>
      </li>
      <li class="nav-item">
         <%= link_to "Searcher", searcher_pages_path, class:"nav-link" %>
      </li>
      <li class="nav-item">
         <%= link_to 'New Post', new_post_path, class:"nav-link" %>
      </li>
      <% if current_user.admin %>
      <li class="nav-item">
         <%= link_to "Users Table", pages_tabl_path, class:"nav-link" %>
      </li>
      <%end%>
    </ul>
  </div>
</nav>

app/views/posts/edit.html.erb
<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<head><link href="//netdna.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script></head>
<link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.1.0/css/font-awesome.min.css"/>
<% if current_user %>
 <%= render 'posts/navsing' %>
<% else %>
  <%=render 'posts/nav' %>
<% end %>
    <% @posts.each do |post| %>
      <div class="container">
          <div class="well">
              <div class="media">
                <a class="pull-left" href="#">
                <%- if post.image.attached? %>
                <div style="width:300px; height: auto">
                <%=image_tag(post.image, style: 'width:100%') %>
                </div>
                <%-end%>
              </a>
              <div class="media-body">
                <h4 class="media-heading"><%= post.title %></h4>
                  <p class="text-right"><%= post.user.username %></p>
                  <p><%= post.description %></p>
                  <ul class="list-inline list-unstyled">
  <li><span><p><i class="fa fa-thumbs-up fa-1x"> <%= post.get_upvotes.size %> likes</i></p></span></li>
                    <li>|</li>
                    <span><i class="glyphicon glyphicon-comment"></i> <%= pluralize(post.comments.count, "comment") %></span>
                    <li>|</li>
                    <li><span><p></p><%= link_to 'Show', post, class:"btn btn-secondary" %></span></li>
                    <li>|</li>
              </ul>
              <p style="font-size: 25px;"> Price: <%= post.price %></p>
               </div>
            </div>
          </div>
        </div>
    <% end %> 

app/views/posts/new.html.erb
 <%= render 'form', post: @post %>
<div class="back-control">
<%= link_to 'Back', posts_path, class:"btn btn-secondary btn-lg btn-block" %>
</div>

app/views/posts/show.html.erb
<head><link href="//netdna.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script></head>
<link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.1.0/css/font-awesome.min.css"/>
<% if current_user %>
 <%= render 'posts/navsing' %>
<% else %>
  <%=render 'posts/nav' %>
<% end %>
<div class="container">
          <div class="well">
              <div class="media">
                <a class="pull-left" href="#">
                <%- if @post.image.attached? %>
                <div style="width:400px; height: auto">
                <%=image_tag(@post.image, style: 'width:100%') %>
                </div>
                <%-end%>
              </a>
              <div class="media-body">
                <h4 class="media-heading"><%= @post.title %></h4>
                  <p class="text-right"><%= @post.user.username %></p>
                  <p><%= @post.description %></p>
                  <ul class="list-inline list-unstyled">
                    <%=link_to like_post_path(@post), class:"like-btn", method: :put, remote: :true do %>
                      <div>
                        <span><p><i class="fa fa-thumbs-up fa-3x"></i></p></span>
                      </div>            
                    <% end %>
                    <li><span class="likes-count"><%= @post.get_upvotes.size %> likes</span></li>
                    <li>|</li>
                    <span><i class="glyphicon glyphicon-comment"></i> <%= pluralize(@post.comments.count, "comment") %></span>
                    <li>|</li>
              </ul>
              <p style="font-size: 25px;"> Price: <%= @post.price %></p>
               </div>
            </div>
          </div>
        </div>

<div class="back-control">
<%= link_to 'Back', posts_path, class:"btn btn-secondary btn-lg btn-block" %>
</div>
<br>
<h2 style="font-size: 25px;">Add your comment!</h2>
<br>
<%= form_with model: [@post,@comment] do |f| %>
  <div class="comment-control">
    <div class="comment-label" style="font-size: 25px;" >
  <%= f.label :Comment,class:"col-4 col-form-label" %>
  <br>
  </div>
    <div class="col-8">
      <%= f.text_area :body, class:"form-control"%>
    </div>
  </div>
  <div class=" comment-button">
<%= f.submit "Comment", class:"btn btn-secondary" %>
</div>
<% end %>
<div id="comment_pane">
<% @comments.each do |comment| %>
  <%= render 'comments/comment', comment: comment %>
<% end %>
</div>



 

app/views/posts/vote.js.erb
<% if current_user.liked? @post %>
     $('.like-btn').removeClass('liked');
<%else%>
     $('.like-btn').addClass('like-btn');
<%end%>
     $('.likes-count').html("<%=@post.get_upvotes.size %>")